In [3]:
#question1
import numpy as np

In [4]:
a=np.random.rand(10,1)

In [5]:
a

array([[ 0.98422042],
       [ 0.75627749],
       [ 0.42169778],
       [ 0.47964782],
       [ 0.9920277 ],
       [ 0.14951763],
       [ 0.47522633],
       [ 0.32627828],
       [ 0.94605167],
       [ 0.88218333]])

In [6]:
np.mean(a)

0.64131284567945757

In [7]:
#question 2
a=np.random.rand(20,1)

In [8]:
a

array([[ 0.44391545],
       [ 0.2020102 ],
       [ 0.92626476],
       [ 0.68865637],
       [ 0.84415054],
       [ 0.87301745],
       [ 0.80121869],
       [ 0.14222614],
       [ 0.83087055],
       [ 0.19578176],
       [ 0.08316556],
       [ 0.85765021],
       [ 0.88806977],
       [ 0.17510285],
       [ 0.76235203],
       [ 0.62257425],
       [ 0.44155759],
       [ 0.3613564 ],
       [ 0.04615696],
       [ 0.74548225]])

In [9]:
np.var(a)

0.093736564675646727

In [10]:
np.std(a)

0.30616427726899609

In [11]:
#question 3
A=np.random.rand(10,20)

In [12]:
B=np.random.rand(20,25)

In [13]:
A.dot(B)

array([[ 4.38200517,  4.50040689,  4.42339429,  4.24602779,  3.54868856,
         6.64646275,  4.60576239,  5.46781746,  4.06731818,  5.9673453 ,
         4.55408134,  5.14196759,  5.85741181,  5.42765193,  5.06346067,
         5.5194476 ,  5.42761896,  4.54197278,  4.27737948,  4.42694746,
         5.84515182,  5.63372204,  5.55880236,  5.31481896,  3.9959851 ],
       [ 4.36305692,  3.26635028,  5.09068547,  4.8184136 ,  3.14834886,
         5.70980263,  3.31401117,  5.43105137,  3.49429665,  5.25321736,
         3.17322861,  4.55226556,  5.33442289,  4.74474847,  4.40793366,
         4.58112347,  4.7909965 ,  3.69369945,  3.37308058,  2.84214085,
         5.40579071,  4.75591607,  4.55049757,  4.15819158,  4.31038058],
       [ 5.7431533 ,  5.38632492,  6.05349919,  5.70065821,  4.89874078,
         8.1191524 ,  5.89453482,  7.69004651,  5.28040196,  7.05098664,
         5.50613993,  6.45754518,  7.09942783,  7.1407952 ,  6.04356462,
         7.33727161,  6.38637474,  4.78668116,  4

In [14]:
np.sum(A)

99.039584134227937

In [44]:
#question 4
A=np.arange(10).reshape(10,1)
a

array([[ 0.44391545],
       [ 0.2020102 ],
       [ 0.92626476],
       [ 0.68865637],
       [ 0.84415054],
       [ 0.87301745],
       [ 0.80121869],
       [ 0.14222614],
       [ 0.83087055],
       [ 0.19578176],
       [ 0.08316556],
       [ 0.85765021],
       [ 0.88806977],
       [ 0.17510285],
       [ 0.76235203],
       [ 0.62257425],
       [ 0.44155759],
       [ 0.3613564 ],
       [ 0.04615696],
       [ 0.74548225]])

In [45]:
1/(1+np.exp(-a))

array([[ 0.60919161],
       [ 0.5503315 ],
       [ 0.71631687],
       [ 0.66566796],
       [ 0.69933865],
       [ 0.70537318],
       [ 0.69023511],
       [ 0.53549672],
       [ 0.69653897],
       [ 0.5487897 ],
       [ 0.52077942],
       [ 0.70216948],
       [ 0.70849168],
       [ 0.5436642 ],
       [ 0.68186417],
       [ 0.65080379],
       [ 0.60863011],
       [ 0.58936874],
       [ 0.51153719],
       [ 0.67819351]])